FROM golang:1.19.3
WORKDIR /app
RUN apt-get update; \
apt-get install -y wget unzip
RUN wget -P /tmp https://github.com/protocolbuffers/protobuf/releases/download/v21.9/protoc-21.9-linux-x86_64.zip
RUN unzip -o /tmp/protoc-21.9-linux-x86_64.zip -d ./third_party
RUN wget -P /tmp https://github.com/googleapis/googleapis/archive/refs/heads/master.zip
RUN unzip -Cjo /tmp/master.zip \
*/api/annotations.proto \
*/api/field_behavior.proto \
*/api/http.proto \
*/api/httpbody.proto \
-d ./third_party/include/google/api/
#
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.14
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.14
#
RUN mkdir -p ./transport/protobuf/certificate ./transport/openapi/certificate /result
COPY ./api/proto/* ./api/proto/
RUN third_party/bin/protoc \
-Iapi/proto \
-Ithird_party/include \
--proto_path=api/proto \
--go_out=transport/protobuf/certificate \
--go_opt=paths=source_relative \
--go-grpc_out=transport/protobuf/certificate \
--go-grpc_opt=paths=source_relative \
--grpc-gateway_out=transport/protobuf/certificate \
--grpc-gateway_opt=paths=source_relative \
--grpc-gateway_opt=generate_unbound_methods=true \
--openapiv2_out=transport/openapi/certificate \
api/proto/*.proto
#
ENTRYPOINT cp -R /app/transport /result/
