FROM golang:1.19.3
WORKDIR /app
RUN apt-get update; \
apt-get install -y wget unzip
RUN wget -P /tmp https://github.com/protocolbuffers/protobuf/releases/download/v21.9/protoc-21.9-linux-x86_64.zip
RUN unzip /tmp/protoc-21.9-linux-x86_64.zip -d ./third_party
#
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
#
RUN mkdir -p ./protobuf/transport/certificate /result
COPY ./api/proto/* ./api/proto/
RUN third_party/bin/protoc \
-Iapi/proto \
-Ithird_party/include \
--proto_path=api/proto \
--go_out=protobuf/transport/certificate \
--go_opt=paths=source_relative \
--go-grpc_out=protobuf/transport/certificate \
--go-grpc_opt=paths=source_relative \
api/proto/*.proto
#
ENTRYPOINT cp /app/protobuf/transport/certificate/* /result/
